@file:Suppress("MagicNumber")

package com.comst19.dambom.core.designsystem

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val LightPrimary = Color(0xFF1B64DA)
private val LightOnPrimary = Color(0xFFFFFFFF)
private val LightPrimaryContainer = Color(0xFFE8F3FF)
private val LightOnPrimaryContainer = Color(0xFF194AA6)
private val LightSecondary = Color(0xFF4E5968)
private val LightOnSecondary = Color(0xFFFFFFFF)
private val LightSecondaryContainer = Color(0xFFF2F4F6)
private val LightOnSecondaryContainer = Color(0xFF333D4B)
private val LightTertiary = Color(0xFF029359)
private val LightOnTertiary = Color(0xFFFFFFFF)
private val LightTertiaryContainer = Color(0xFFDFF7ED)
private val LightOnTertiaryContainer = Color(0xFF006C47)
private val LightError = Color(0xFFE42939)
private val LightOnError = Color(0xFFFFFFFF)
private val LightErrorContainer = Color(0xFFFFE0E3)
private val LightOnErrorContainer = Color(0xFF7A1821)
private val LightBackground = Color(0xFFFFFFFF)
private val LightOnBackground = Color(0xFF191F28)
private val LightSurface = Color(0xFFFFFFFF)
private val LightOnSurface = Color(0xFF191F28)
private val LightSurfaceVariant = Color(0xFFF2F4F6)
private val LightOnSurfaceVariant = Color(0xFF4E5968)
private val LightSurfaceBright = Color(0xFFFFFFFF)
private val LightSurfaceDim = Color(0xFFF2F4F6)
private val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
private val LightSurfaceContainerLow = Color(0xFFF9FAFB)
private val LightSurfaceContainer = Color(0xFFF2F4F6)
private val LightSurfaceContainerHigh = Color(0xFFE5E8EB)
private val LightSurfaceContainerHighest = Color(0xFFD1D6DB)
private val LightOutline = Color(0xFF8B95A1)
private val LightOutlineVariant = Color(0xFFE5E8EB)
private val LightInverseSurface = Color(0xFF333D4B)
private val LightInverseOnSurface = Color(0xFFF9FAFB)
private val LightInversePrimary = Color(0xFF4593FC)
private val LightSurfaceTint = Color(0xFF1B64DA)

private val DarkPrimary = Color(0xFF4593FC)
private val DarkOnPrimary = Color(0xFF101C2D)
private val DarkPrimaryContainer = Color(0xFF1B64DA)
private val DarkOnPrimaryContainer = Color(0xFFF9FAFB)
private val DarkSecondary = Color(0xFFB0B8C1)
private val DarkOnSecondary = Color(0xFF191F28)
private val DarkSecondaryContainer = Color(0xFF333D4B)
private val DarkOnSecondaryContainer = Color(0xFFF2F4F6)
private val DarkTertiary = Color(0xFF15C47E)
private val DarkOnTertiary = Color(0xFF191F28)
private val DarkTertiaryContainer = Color(0xFF006C47)
private val DarkOnTertiaryContainer = Color(0xFFDFF7ED)
private val DarkError = Color(0xFFF66570)
private val DarkOnError = Color(0xFF191F28)
private val DarkErrorContainer = Color(0xFF7A1821)
private val DarkOnErrorContainer = Color(0xFFFFE0E3)
private val DarkBackground = Color(0xFF191F28)
private val DarkOnBackground = Color(0xFFF9FAFB)
private val DarkSurface = Color(0xFF191F28)
private val DarkOnSurface = Color(0xFFF9FAFB)
private val DarkSurfaceVariant = Color(0xFF333D4B)
private val DarkOnSurfaceVariant = Color(0xFFB0B8C1)
private val DarkSurfaceBright = Color(0xFF4E5968)
private val DarkSurfaceDim = Color(0xFF191F28)
private val DarkSurfaceContainerLowest = Color(0xFF14191F)
private val DarkSurfaceContainerLow = Color(0xFF202632)
private val DarkSurfaceContainer = Color(0xFF252C35)
private val DarkSurfaceContainerHigh = Color(0xFF333D4B)
private val DarkSurfaceContainerHighest = Color(0xFF4E5968)
private val DarkOutline = Color(0xFF8B95A1)
private val DarkOutlineVariant = Color(0xFF4E5968)
private val DarkInverseSurface = Color(0xFFF2F4F6)
private val DarkInverseOnSurface = Color(0xFF333D4B)
private val DarkInversePrimary = Color(0xFF1B64DA)
private val DarkSurfaceTint = Color(0xFF4593FC)

private val Scrim = Color(0xFF000000)
private val PrimaryFixed = Color(0xFFE8F3FF)
private val PrimaryFixedDim = Color(0xFF90C2FF)
private val OnPrimaryFixed = Color(0xFF194AA6)
private val OnPrimaryFixedVariant = Color(0xFF1B64DA)
private val SecondaryFixed = Color(0xFFF2F4F6)
private val SecondaryFixedDim = Color(0xFFD1D6DB)
private val OnSecondaryFixed = Color(0xFF191F28)
private val OnSecondaryFixedVariant = Color(0xFF4E5968)
private val TertiaryFixed = Color(0xFFDFF7ED)
private val TertiaryFixedDim = Color(0xFF86E8BE)
private val OnTertiaryFixed = Color(0xFF005C3C)
private val OnTertiaryFixedVariant = Color(0xFF029359)

val DambomLightColorScheme =
    lightColorScheme(
        primary = LightPrimary,
        onPrimary = LightOnPrimary,
        primaryContainer = LightPrimaryContainer,
        onPrimaryContainer = LightOnPrimaryContainer,
        inversePrimary = LightInversePrimary,
        secondary = LightSecondary,
        onSecondary = LightOnSecondary,
        secondaryContainer = LightSecondaryContainer,
        onSecondaryContainer = LightOnSecondaryContainer,
        tertiary = LightTertiary,
        onTertiary = LightOnTertiary,
        tertiaryContainer = LightTertiaryContainer,
        onTertiaryContainer = LightOnTertiaryContainer,
        background = LightBackground,
        onBackground = LightOnBackground,
        surface = LightSurface,
        onSurface = LightOnSurface,
        surfaceVariant = LightSurfaceVariant,
        onSurfaceVariant = LightOnSurfaceVariant,
        surfaceTint = LightSurfaceTint,
        inverseSurface = LightInverseSurface,
        inverseOnSurface = LightInverseOnSurface,
        error = LightError,
        onError = LightOnError,
        errorContainer = LightErrorContainer,
        onErrorContainer = LightOnErrorContainer,
        outline = LightOutline,
        outlineVariant = LightOutlineVariant,
        scrim = Scrim,
        surfaceBright = LightSurfaceBright,
        surfaceDim = LightSurfaceDim,
        surfaceContainerLowest = LightSurfaceContainerLowest,
        surfaceContainerLow = LightSurfaceContainerLow,
        surfaceContainer = LightSurfaceContainer,
        surfaceContainerHigh = LightSurfaceContainerHigh,
        surfaceContainerHighest = LightSurfaceContainerHighest,
        primaryFixed = PrimaryFixed,
        primaryFixedDim = PrimaryFixedDim,
        onPrimaryFixed = OnPrimaryFixed,
        onPrimaryFixedVariant = OnPrimaryFixedVariant,
        secondaryFixed = SecondaryFixed,
        secondaryFixedDim = SecondaryFixedDim,
        onSecondaryFixed = OnSecondaryFixed,
        onSecondaryFixedVariant = OnSecondaryFixedVariant,
        tertiaryFixed = TertiaryFixed,
        tertiaryFixedDim = TertiaryFixedDim,
        onTertiaryFixed = OnTertiaryFixed,
        onTertiaryFixedVariant = OnTertiaryFixedVariant,
    )

val DambomDarkColorScheme =
    darkColorScheme(
        primary = DarkPrimary,
        onPrimary = DarkOnPrimary,
        primaryContainer = DarkPrimaryContainer,
        onPrimaryContainer = DarkOnPrimaryContainer,
        inversePrimary = DarkInversePrimary,
        secondary = DarkSecondary,
        onSecondary = DarkOnSecondary,
        secondaryContainer = DarkSecondaryContainer,
        onSecondaryContainer = DarkOnSecondaryContainer,
        tertiary = DarkTertiary,
        onTertiary = DarkOnTertiary,
        tertiaryContainer = DarkTertiaryContainer,
        onTertiaryContainer = DarkOnTertiaryContainer,
        background = DarkBackground,
        onBackground = DarkOnBackground,
        surface = DarkSurface,
        onSurface = DarkOnSurface,
        surfaceVariant = DarkSurfaceVariant,
        onSurfaceVariant = DarkOnSurfaceVariant,
        surfaceTint = DarkSurfaceTint,
        inverseSurface = DarkInverseSurface,
        inverseOnSurface = DarkInverseOnSurface,
        error = DarkError,
        onError = DarkOnError,
        errorContainer = DarkErrorContainer,
        onErrorContainer = DarkOnErrorContainer,
        outline = DarkOutline,
        outlineVariant = DarkOutlineVariant,
        scrim = Scrim,
        surfaceBright = DarkSurfaceBright,
        surfaceDim = DarkSurfaceDim,
        surfaceContainerLowest = DarkSurfaceContainerLowest,
        surfaceContainerLow = DarkSurfaceContainerLow,
        surfaceContainer = DarkSurfaceContainer,
        surfaceContainerHigh = DarkSurfaceContainerHigh,
        surfaceContainerHighest = DarkSurfaceContainerHighest,
        primaryFixed = PrimaryFixed,
        primaryFixedDim = PrimaryFixedDim,
        onPrimaryFixed = OnPrimaryFixed,
        onPrimaryFixedVariant = OnPrimaryFixedVariant,
        secondaryFixed = SecondaryFixed,
        secondaryFixedDim = SecondaryFixedDim,
        onSecondaryFixed = OnSecondaryFixed,
        onSecondaryFixedVariant = OnSecondaryFixedVariant,
        tertiaryFixed = TertiaryFixed,
        tertiaryFixedDim = TertiaryFixedDim,
        onTertiaryFixed = OnTertiaryFixed,
        onTertiaryFixedVariant = OnTertiaryFixedVariant,
    )
