@file:Suppress("MagicNumber")

package com.comst19.dambom.core.designsystem

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val LightPrimary = Color(0xFF2563EB)
private val LightOnPrimary = Color(0xFFFFFFFF)
private val LightPrimaryContainer = Color(0xFFDBEAFE)
private val LightOnPrimaryContainer = Color(0xFF1E3A8A)
private val LightSecondary = Color(0xFF475569)
private val LightOnSecondary = Color(0xFFFFFFFF)
private val LightSecondaryContainer = Color(0xFFE2E8F0)
private val LightOnSecondaryContainer = Color(0xFF1E293B)
private val LightTertiary = Color(0xFF0F766E)
private val LightOnTertiary = Color(0xFFFFFFFF)
private val LightTertiaryContainer = Color(0xFFCCFBF1)
private val LightOnTertiaryContainer = Color(0xFF134E4A)
private val LightError = Color(0xFFBA1A1A)
private val LightOnError = Color(0xFFFFFFFF)
private val LightErrorContainer = Color(0xFFFFDAD6)
private val LightOnErrorContainer = Color(0xFF410002)
private val LightBackground = Color(0xFFF8FAFC)
private val LightOnBackground = Color(0xFF0F172A)
private val LightSurface = Color(0xFFFFFFFF)
private val LightOnSurface = Color(0xFF0F172A)
private val LightSurfaceVariant = Color(0xFFE2E8F0)
private val LightOnSurfaceVariant = Color(0xFF475569)
private val LightSurfaceBright = Color(0xFFFFFFFF)
private val LightSurfaceDim = Color(0xFFE2E8F0)
private val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
private val LightSurfaceContainerLow = Color(0xFFF8FAFC)
private val LightSurfaceContainer = Color(0xFFF1F5F9)
private val LightSurfaceContainerHigh = Color(0xFFE9EEF5)
private val LightSurfaceContainerHighest = Color(0xFFE2E8F0)
private val LightOutline = Color(0xFF64748B)
private val LightOutlineVariant = Color(0xFFCBD5E1)
private val LightInverseSurface = Color(0xFF1E293B)
private val LightInverseOnSurface = Color(0xFFF8FAFC)
private val LightInversePrimary = Color(0xFF93C5FD)
private val LightSurfaceTint = Color(0xFF2563EB)

private val DarkPrimary = Color(0xFF60A5FA)
private val DarkOnPrimary = Color(0xFF0F172A)
private val DarkPrimaryContainer = Color(0xFF1E3A8A)
private val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
private val DarkSecondary = Color(0xFFCBD5E1)
private val DarkOnSecondary = Color(0xFF1E293B)
private val DarkSecondaryContainer = Color(0xFF334155)
private val DarkOnSecondaryContainer = Color(0xFFE2E8F0)
private val DarkTertiary = Color(0xFF5EEAD4)
private val DarkOnTertiary = Color(0xFF134E4A)
private val DarkTertiaryContainer = Color(0xFF115E59)
private val DarkOnTertiaryContainer = Color(0xFFCCFBF1)
private val DarkError = Color(0xFFFFB4AB)
private val DarkOnError = Color(0xFF690005)
private val DarkErrorContainer = Color(0xFF93000A)
private val DarkOnErrorContainer = Color(0xFFFFDAD6)
private val DarkBackground = Color(0xFF0F172A)
private val DarkOnBackground = Color(0xFFF8FAFC)
private val DarkSurface = Color(0xFF111827)
private val DarkOnSurface = Color(0xFFF8FAFC)
private val DarkSurfaceVariant = Color(0xFF334155)
private val DarkOnSurfaceVariant = Color(0xFFCBD5E1)
private val DarkSurfaceBright = Color(0xFF334155)
private val DarkSurfaceDim = Color(0xFF0F172A)
private val DarkSurfaceContainerLowest = Color(0xFF020617)
private val DarkSurfaceContainerLow = Color(0xFF111827)
private val DarkSurfaceContainer = Color(0xFF1E293B)
private val DarkSurfaceContainerHigh = Color(0xFF273449)
private val DarkSurfaceContainerHighest = Color(0xFF334155)
private val DarkOutline = Color(0xFF94A3B8)
private val DarkOutlineVariant = Color(0xFF475569)
private val DarkInverseSurface = Color(0xFFE2E8F0)
private val DarkInverseOnSurface = Color(0xFF1E293B)
private val DarkInversePrimary = Color(0xFF2563EB)
private val DarkSurfaceTint = Color(0xFF60A5FA)

private val Scrim = Color(0xFF000000)
private val PrimaryFixed = Color(0xFFDBEAFE)
private val PrimaryFixedDim = Color(0xFF93C5FD)
private val OnPrimaryFixed = Color(0xFF172554)
private val OnPrimaryFixedVariant = Color(0xFF1E40AF)
private val SecondaryFixed = Color(0xFFE2E8F0)
private val SecondaryFixedDim = Color(0xFFCBD5E1)
private val OnSecondaryFixed = Color(0xFF0F172A)
private val OnSecondaryFixedVariant = Color(0xFF334155)
private val TertiaryFixed = Color(0xFFCCFBF1)
private val TertiaryFixedDim = Color(0xFF5EEAD4)
private val OnTertiaryFixed = Color(0xFF042F2E)
private val OnTertiaryFixedVariant = Color(0xFF115E59)

internal val DambomLightColorScheme =
    lightColorScheme(
        primary = LightPrimary,
        onPrimary = LightOnPrimary,
        primaryContainer = LightPrimaryContainer,
        onPrimaryContainer = LightOnPrimaryContainer,
        inversePrimary = LightInversePrimary,
        secondary = LightSecondary,
        onSecondary = LightOnSecondary,
        secondaryContainer = LightSecondaryContainer,
        onSecondaryContainer = LightOnSecondaryContainer,
        tertiary = LightTertiary,
        onTertiary = LightOnTertiary,
        tertiaryContainer = LightTertiaryContainer,
        onTertiaryContainer = LightOnTertiaryContainer,
        background = LightBackground,
        onBackground = LightOnBackground,
        surface = LightSurface,
        onSurface = LightOnSurface,
        surfaceVariant = LightSurfaceVariant,
        onSurfaceVariant = LightOnSurfaceVariant,
        surfaceTint = LightSurfaceTint,
        inverseSurface = LightInverseSurface,
        inverseOnSurface = LightInverseOnSurface,
        error = LightError,
        onError = LightOnError,
        errorContainer = LightErrorContainer,
        onErrorContainer = LightOnErrorContainer,
        outline = LightOutline,
        outlineVariant = LightOutlineVariant,
        scrim = Scrim,
        surfaceBright = LightSurfaceBright,
        surfaceDim = LightSurfaceDim,
        surfaceContainerLowest = LightSurfaceContainerLowest,
        surfaceContainerLow = LightSurfaceContainerLow,
        surfaceContainer = LightSurfaceContainer,
        surfaceContainerHigh = LightSurfaceContainerHigh,
        surfaceContainerHighest = LightSurfaceContainerHighest,
        primaryFixed = PrimaryFixed,
        primaryFixedDim = PrimaryFixedDim,
        onPrimaryFixed = OnPrimaryFixed,
        onPrimaryFixedVariant = OnPrimaryFixedVariant,
        secondaryFixed = SecondaryFixed,
        secondaryFixedDim = SecondaryFixedDim,
        onSecondaryFixed = OnSecondaryFixed,
        onSecondaryFixedVariant = OnSecondaryFixedVariant,
        tertiaryFixed = TertiaryFixed,
        tertiaryFixedDim = TertiaryFixedDim,
        onTertiaryFixed = OnTertiaryFixed,
        onTertiaryFixedVariant = OnTertiaryFixedVariant,
    )

internal val DambomDarkColorScheme =
    darkColorScheme(
        primary = DarkPrimary,
        onPrimary = DarkOnPrimary,
        primaryContainer = DarkPrimaryContainer,
        onPrimaryContainer = DarkOnPrimaryContainer,
        inversePrimary = DarkInversePrimary,
        secondary = DarkSecondary,
        onSecondary = DarkOnSecondary,
        secondaryContainer = DarkSecondaryContainer,
        onSecondaryContainer = DarkOnSecondaryContainer,
        tertiary = DarkTertiary,
        onTertiary = DarkOnTertiary,
        tertiaryContainer = DarkTertiaryContainer,
        onTertiaryContainer = DarkOnTertiaryContainer,
        background = DarkBackground,
        onBackground = DarkOnBackground,
        surface = DarkSurface,
        onSurface = DarkOnSurface,
        surfaceVariant = DarkSurfaceVariant,
        onSurfaceVariant = DarkOnSurfaceVariant,
        surfaceTint = DarkSurfaceTint,
        inverseSurface = DarkInverseSurface,
        inverseOnSurface = DarkInverseOnSurface,
        error = DarkError,
        onError = DarkOnError,
        errorContainer = DarkErrorContainer,
        onErrorContainer = DarkOnErrorContainer,
        outline = DarkOutline,
        outlineVariant = DarkOutlineVariant,
        scrim = Scrim,
        surfaceBright = DarkSurfaceBright,
        surfaceDim = DarkSurfaceDim,
        surfaceContainerLowest = DarkSurfaceContainerLowest,
        surfaceContainerLow = DarkSurfaceContainerLow,
        surfaceContainer = DarkSurfaceContainer,
        surfaceContainerHigh = DarkSurfaceContainerHigh,
        surfaceContainerHighest = DarkSurfaceContainerHighest,
        primaryFixed = PrimaryFixed,
        primaryFixedDim = PrimaryFixedDim,
        onPrimaryFixed = OnPrimaryFixed,
        onPrimaryFixedVariant = OnPrimaryFixedVariant,
        secondaryFixed = SecondaryFixed,
        secondaryFixedDim = SecondaryFixedDim,
        onSecondaryFixed = OnSecondaryFixed,
        onSecondaryFixedVariant = OnSecondaryFixedVariant,
        tertiaryFixed = TertiaryFixed,
        tertiaryFixedDim = TertiaryFixedDim,
        onTertiaryFixed = OnTertiaryFixed,
        onTertiaryFixedVariant = OnTertiaryFixedVariant,
    )
